fortune_makers/fortune/urls.py
from django.urls import path
from django.urls import reverse
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'fortune'

urlpatterns = [
    #path('admin/', admin.site.urls),
    # path('summary/', views.summary, name='summary'),
    path('get_mpesa_records/', views.get_mpesa_records, name='mpesa_records'),
    # path('', views.homepage, name = 'homepage'),
    path('homepage/', views.homepage, name = 'homepage'),
    path('', views.homepage, name='homepage'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('terms/', views.terms_view, name='terms'),
    path('faqs/', views.faqs_view, name='faqs'),

    path('products/', views.search_products, name='products'),    
    path('payment/', views.payment_view, name='payment'),
    path('summary/', views.summary_view, name='summary'),
    path('wallet/', views.wallet_view, name='wallet'),
    path('logged_in_users/', views.logged_in_users_view, name='logged_in_users'),
    path('quick_guide/', views.quick_guide_view, name='quick_guide'),
    # path('index/', views.index_view, name='index'),
    path('mpesa/', views.mpesa_view, name='mpesa'),

    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name= 'logout'),

    
    # path('invoice/', views.invoice_view, name='invoice'),
    # path('my_profile/', views.my_profile_view, name='my_profile'),
    # path('<str:ref_code>/', views.my_profile_view, name='my_profile'),
    # path('<str:ref_code>/', views.my_profile_view, name='my_profile'),
    path('my_referral/', views.my_referral_view, name='my_referral'),
    path('my_invoices/', views.my_invoices_view, name='my_invoices'),
    path('my_investments/', views.my_investments_view, name='my_investments'),
    path('download_invoice_csv/', views.generate_invoice_csv, name='invoice_csv_download'),
    path('download_invoice_pdf/', views.generate_invoice_pdf, name='invoice_pdf_download'),

    # path('register/', views.register_request, name='register'),
    # path('login/', views.login_request, name='login'),
    # path('logout/', views.logout_request, name= 'logout'),

    path('product1/', views.p1_view, name='product1'),
    path('product2/', views.p2_view, name='product2'),
    path('product3/', views.p3_view, name='product3'),
    path('product4/', views.p4_view, name='product4'),
    path('product5/', views.p5_view, name='product5'),
    path('product6/', views.p6_view, name='product6'),

    path('payment/', views.payment_view, name='payment'),
    # path('complete/', views.complete_view, name='complete'),        

    path('my_profile/', views.my_profile_view, name='my_profile'),
    path('<str:ref_code>/', views.my_profile_view, name='my_profile'),

    
    # path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    # path('change/password/', ChangePasswordView.as_view(), name='change_password'),
]

fortune_makers/fortune_makers/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # path('ehub-secret/', admin.site.urls),
    # path('ehub-backdoor/', admin.site.urls),
    # path('', IndexPageView.as_view(), name='index'),
    path('', include('fortune.urls')),
    # path('', include('main.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    ]

fortune_makers/fortune/forms.py
from django import forms
# from bootstrap_daterangepicker import widgets, fields

from .models import Product, Payment, Withdraw
from django.contrib.auth.forms import UserCreationForm
from .models import User

# registration
# from datetime import timedelta

# from django.forms import ValidationError
# from django.conf import settings
# from django.contrib.auth.models import User
# from django.utils import timezone
# from django.db.models import Q
# from django.utils.translation import gettext_lazy as _


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)

        for fieldname in ['email', 'username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']
        if commit:
            user.save()
        return user


class MpesaForm(forms.Form):
    mpesa_code = forms.CharField(max_length = 200)

    def clean_code(self):
        mpesa_code = self.cleaned_data['mpesa_code']
        return mpesa_code

class PaymentCreate(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('package', 'amount', 'mpesa_code', 'created_date', 'phn_number', 'status')


class WithdrawForm(forms.Form):
    amount = forms.IntegerField(label='Enter the Amount to Withdraw')
    phn_number = forms.CharField(label='Enter the Phone Number', max_length = 200)

    def clean_code(self):
        amount = self.cleaned_data['amount']
        phn_number = self.cleaned_data['phn_number']
        return amount,phn_number

class WithdrawCreate(forms.ModelForm):
    class Meta:
        model = Withdraw
        fields = ('phn_number', 'amount', 'fee', 'created_date', 'status')

class WithdrawFormReferral(forms.Form):
    amount = forms.IntegerField(label='Enter the points to convert')
    phn_number = forms.CharField(max_length = 200)

    def clean_code(self):
        amount = self.cleaned_data['amount']
        phn_number = self.cleaned_data['phn_number']
        return amount,phn_number

class WithdrawCreateReferral(forms.ModelForm):
    class Meta:
        model = Withdraw
        fields = ('phn_number', 'amount', 'created_date', 'status')

fortune_makers/fortune/views.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from .models import Product, Payment, Profile, Withdraw
from .utils import generate_ref_code
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# for csv generation
import csv
# for pdf generation
from django.template.loader import render_to_string
# from weasyprint import HTML
import tempfile
from .forms import NewUserForm, PaymentCreate, WithdrawForm, MpesaForm, WithdrawCreate, WithdrawFormReferral
# Create your views here.
from django.http import HttpResponse
from django.db.models import Avg, Max, Min, Sum
from django.contrib import messages

from datetime import datetime
from datetime import timedelta
import math

# registration
from django.contrib.auth.models import Group, User
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib.auth import login, logout, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
# from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings


from django.contrib.sessions.models import Session
from importlib import import_module
from django.conf import settings

def homepage(request):
    return render(request, 'fortune/homepage.html')

def privacy_view(request):
    return render(request, 'fortune/privacy.html')

def terms_view(request):
    return render(request, 'fortune/terms.html')

def faqs_view(request):
    return render(request, 'fortune/faqs.html')

def check_activated(request, user):
    mpesa_records = Payment.objects.all().order_by("-created_date").values()
    total_in = mpesa_records.filter(status=True).values(
            'created_date','phn_number','mpesa_code','package','status','amount')
    total_inv = total_in.filter(paid_by=user)[:1]

    amount2 = []
    if total_inv:
        for i in total_inv:
            amount = i['amount']
            amount2.append(amount)
    if len(amount2) > 0:
        return True
    else:
        return False

@login_required
def payment_view(request):
    user = request.user
    user_id = user.id
    account_number = int(user_id+10000)
    end_subscription = None
    # Find the end of subscription
    record = Payment.objects.filter(reference=account_number).values()
    if record.count() > 0:
        sorted_record = sorted(record, key = lambda i: i['created_at'])
        record_date = sorted_record[-1]['created_at'].date()
        end_subscription = record_date + timedelta(days=30)
    return render(request, 'fortune/payment.html', {
     'end_subscription':end_subscription})

@login_required
def get_mpesa_records(request):
    user = request.user
    mpesa_records = Payment.objects.all().order_by("-created_date")
    total_inv = []
    total_invoices = 0
    if mpesa_records.count() > 0:
        total_inv = mpesa_records.values(
            'created_date','phn_number','mpesa_code','package','amount')
        total_invoice = total_inv.aggregate(price_sum=Sum('amount'))
        total_invoices = int(total_invoice['price_sum'])
    else:
            total_invoices = 0

    return render(request, 'fortune/fortune_mpesa_records.html', {
        'mpesa_records': mpesa_records, 'total_invoices': total_invoices})


# def my_referral_view(request):
#     if not request.user.is_authenticated:
#         return redirect('fortune:login')

    return render(request, 'fortune/my_referral.html')

def my_invoices_view(request):
    if not request.user.is_authenticated:
        return redirect('fortune:login')
    user = request.user
    mpesa_records = Payment.objects.all().order_by("-created_date")
    total_inv = []
    total_invoices = 0
    if mpesa_records.count() > 0:
        total_inv = mpesa_records.filter(paid_by=user).values(
            'created_date','phn_number','mpesa_code','package','status','amount')
        if total_inv.count()>0:
            total_invoice = total_inv.aggregate(price_sum=Sum('amount'))
            total_invoices = int(total_invoice['price_sum'])
        else:
            total_invoices = 0

    return render(request, 'fortune/my_invoices.html', {
        'total_inv': total_inv, 'total_invoices':total_invoices})


def my_referral_view(request):
    if not request.user.is_authenticated:
        return redirect('fortune:login')

    qs = Profile.objects.all()
    user_list = []
    for profile in qs:
        if profile.recommended_by == request.user:
            user_list.append(profile.user)

    print("users list",user_list)

    m_records = []

    for i in user_list:
        if check_activated(request, i):
            m_records.append(i)

    print("m records",m_records)
    active_referalls=len(m_records)
    total_commission = active_referalls*100

    print("m records",active_referalls)
    # print("======callled====    ")
    if Profile.objects.get(user=request.user) is not None:
        my_recs = Profile.objects.get(user=request.user).get_recommened_profiles()
    else:
        my_recs = {}

    inactive_referrals = set(user_list)-set(m_records)

    return render(request, 'fortune/my_referral.html', {
        'my_recs': my_recs, 'total_commission':total_commission
        , 'm_records':m_records, 'inactive_referrals':inactive_referrals
        , 'user_list':user_list})  


def my_recommendations_view(request):
    profile = Profile.objects.get(user=request.user)
    my_recs = profile.get_recommened_profiles()
    context = {'my_recs': my_recs}
    return render(request, 'profiles/my_profile.html', context)


def my_profile_view(request, *args, **kwargs):
    code = str(kwargs.get('ref_code'))
    print("ref code",code)
    try:
        profile = Profile.objects.get(code=code)
        request.session['ref_profile'] = profile.id
        # print('id', profile.id)
    except:
        pass
    # print(request.session.get_expiry_age())
    # return render(request, 'fortune/index.html')
    return render(request, 'fortune/homepage.html')


def my_investments_view(request):
    if not request.user.is_authenticated:
        return redirect('fortune:login')

    user = request.user
    mpesa_records = Payment.objects.all().order_by("-created_date")
    total_inv = []
    total_invoices = 0
    if mpesa_records.count() > 0:
        total_inv = mpesa_records.filter(paid_by=user).values(
            'created_date','phn_number','mpesa_code','package','status','amount')
        if total_inv.count()>0:
            total_invoice = total_inv.aggregate(price_sum=Sum('amount'))
            total_invoices = int(total_invoice['price_sum'])
        else:
            total_invoices = 0

    return render(request, 'fortune/my_investments.html', {
        'total_inv': total_inv, 'total_invoices':total_invoices})


def generate_invoice_pdf(request):
    if not request.user.is_authenticated:
        return redirect('fortune:login')

    user=request.user
    user_id = user.id
    account_number = int(user_id+10000)
    total = Payment.objects.all()
    total_invoice = total.filter(id=user_id)

    # Rendered
    html_string = render_to_string('fortune/invoice_pdf.html', {'total_invoice': total_invoice})
    html = HTML(string=html_string)
    result = html.write_pdf()

    # Creating http response
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'inline; filename=invoice.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())

    return response


def generate_invoice_csv(request):
    if not request.user.is_authenticated:
        return redirect('fortune:login')

    user=request.user
    user_id = user.id
    account_number = int(user_id+10000)
    total = Payment.objects.all()
    items = total.filter(id=user_id)
    # items = Revenue.objects.all()
    response = HttpResponse(content_type = 'text/csv')
    response['Content-Disposition'] = 'attachment;filename="invoice.csv"'

    writer = csv.writer(response,delimiter=',')
    writer.writerow(['Paid On','Amount', 'First Name', 'Last Name', 'Phone Number', 'Mpesa Code'])
    for obj in items:
        writer.writerow([obj.created_date,obj.amount,obj.first_name,obj.last_name,obj.phn_number,obj.mpesa_code])
 
    return response


def summary_view(request):
    if not request.user.is_authenticated:
        return redirect('fortune:login')

    user = request.user
    ref_codes = Profile.objects.all()
    print("ref codes=======............................",ref_codes)

    my_ref_code = ref_codes.filter(user=user).values('code')
    print("my ref code=======",my_ref_code)
    # my_ref_code2 = 'adcd'
    my_ref_code2 = my_ref_code[0]['code']
    print("my ref code-2--------",my_ref_code2)
    my_host = request.get_host()
    print("my host=========",my_host)
    my_ref_code_url = 'https://'+str(my_host)+'/'+str(my_ref_code2)
    print("my ref code url=========",my_ref_code_url)
          
    mpesa_records = Payment.objects.all().order_by("-created_date")
    total_inv = []
    total_invoices = 0
    total_earnings = 0
    daily_earnings = 0
    total_amount = 0
    total_package = []
    if mpesa_records.count() > 0:

fortune_makers/fortune/templates/fortune/homepage.html
{% load static %}
{% load bootstrap4 %}
{% load humanize %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="css/header.css">  -->
    <link rel="stylesheet" href="{% static 'index/css/header.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <!-- <link rel="stylesheet" href="css/main.css"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.3/css/mdb.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>
      Fortune Makers - Earn Stable Passive Income
  </title>
  <link rel="icon" type="image/x-icon" href="/static/fortune/images/favicon.png">

  <meta name="description" content="Earn stable passive income. Accumulating Wealth Has Never Been This Simple">

  <meta property="og:title" content="Earn Stable Passive Income" />

  <meta property="og:url" content="" />
  <meta property="og:description" content="Earn stable passive income. Accumulating Wealth Has Never Been This Simple" />


  <meta property="og:type" content="article" />



  <meta name="referrer" content="no-referrer-when-downgrade">
</head>


<style type="text/css">
.hm-gradient {
    background-image: linear-gradient(to top, #f3e7e9 0%, #e3eeff 99%, #e3eeff 100%);
}
.darken-grey-text {
    color: #2E2E2E;
}

.navbar .dropdown-menu a:hover {
    color: #616161 !important;
}
.darken-grey-text {
    color: #2E2E2E;
}


</style>
<body class="hm-gradient">
    {% bootstrap_messages %}
    
    <main>
        
        <!--MDB Navbars-->
        <div class="container mt-4">
            <!--Navbar -->
            <nav class="mb-4 navbar navbar-expand-lg navbar-dark purple lighten-1">
                <a class="navbar-brand" href="#"><h3><text style="color:orange";> FORTUNE MAKERS </text> </h3></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-5" aria-controls="navbarSupportedContent-5" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent-5">
                    <ul class="navbar-nav ml-auto nav-flex-icons">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'fortune:summary' %}"><i class="fas fa-tachometer-alt"></i> Dashboard</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'fortune:logout' %}"><i class="fa fa-sign-out"></i>Log Out</a>
                        </li>
                        {% endif %}

                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fortune:login' %}"><i class="fa fa-sign-in"></i>Sign In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>

          <hr class="my-4">
       </div>
    </main>

<style type="text/css">

{% block content %}

/* Centered text */
.centered {
  position: absolute;
  top: 60%;
  left: 35%;
  transform: translate(-50%, -50%);
}

</style>


<div class="container mt-4">
    <!--         <div class="centered">
                <h2><text style="color:black";>Everyday is a Bank Account</text></h2>
            </div> -->
    <img src="/static/fortune/images/becausemoney.png" alt="" class="img-fluid w-100">
</div>


<br>

<div class="container mt-4">
    <hr>
<h1 style="text-align: center;"> HOW IT WORKS </h1>
<hr>
</div>


<div class="container mt-4">
<div class="row text-center">


    <div class="col-sm-12 col-md-4">
        <br>
    <div class="card">
      <div class="card-body">
        <img src="/static/fortune/images/edit.png" width="60" height="60">
        <h5 class="card-title">Register an account</h5>
         <hr>
        <p class="card-text">Open an Account with just your email address.</p>
        <a href="{% url 'fortune:register' %}" class="btn btn-primary">Register Today</a>
      </div>
    </div>
    </div>
<br>
<br>
<br>

    <div class="col-sm-12 col-md-4">
        <br>
    <div class="card">
      <div class="card-body">
        <img src="/static/fortune/images/pointers.png" width="60" height="60">

        <h5 class="card-title">Select a plan to invest</h5>
         <hr>
        <p class="card-text">Choose from any of our investment plans that suite you to invest.</p>
        <a href="{% url 'fortune:register' %}" class="btn btn-primary">Register Today</a>
      </div>
    </div>
    </div>

    <div class="col-sm-12 col-md-4">
    <br>
    <div class="card">
      <div class="card-body">
        <img src="/static/fortune/images/sunbathing.png" width="60" height="60">
        <h5 class="card-title">Wait for returns</h5>
         <hr>
        <p class="card-text">Watch as your investment profit grow on hourly basis.</p>
        <a href="{% url 'fortune:register' %}" class="btn btn-primary">Register Today</a>
      </div>
    </div>
    </div>

</div>
<hr>
</div>

<br>
<br>

<div class="container mt-4">
<h3 style="color:blue; text-align: center;"> OUR INVESTMENTS PLAN </h3>
<p style="text-align: center;"> Get 7.5% profit on all our plans, Offer available for limited time. </p>
<hr>
</div>

<div class="container mt-4">
        <div class="row text-center">
          <div class="col-lg">
            <div class="bg-white rounded shadow-sm"><img src="/static/fortune/images/starter.png" alt="" width="300" height="300">
                <!-- <h5> <a href="" class="text-dark">{{ product1_ui_name }}</a></h5> -->
                <h5> <u>STARTER PACKAGE</u></h5>
                <p class="small text-muted mb-0">Invest in our Starter package and earn 7.5% interest per day. We grant you an unique opportunity to create great wealth</p>
                <h3> KSh 500</h3>

                    <button type="button" class="btn btn-warning btn-rounded">
                        <a href="{% url 'fortune:product1' %}">
                          BUY PACKAGE
                      </a>
                  </button>
               <hr>
          </div>
      </div>


      <div class="col-lg">
        <div class="bg-white rounded shadow-sm"><img src="/static/fortune/images/bronze.png" alt="" width="300" height="300">
            <h5> <u>BRONZE PACKAGE</u></h5>
            <p class="small text-muted mb-0">Bronze package is the best package for people serious in starting their investment journey. Invest in our bronze package and enjoy hyper returns. </p>
            <h3> KSh 1,000</h3>
            <!-- <div class="d-flex align-items-center justify-content-between rounded-pill bg-light px-3 py-2 mt-4"> -->
                <button type="button" class="btn btn-warning btn-rounded">
                    <a href="{% url 'fortune:product2' %}">
                      BUY PACKAGE
                  </a>
              </button>
          <!-- </div> -->
          <hr>
      </div>
  </div>

  <div class="col-lg">
    <div class="bg-white rounded shadow-sm"><img src="/static/fortune/images/silver.png" alt="" width="300" height="300">
        <h5> <u>SILVER PACKAGE</u></h5>
        <p class="small text-muted mb-0">Accumulating wealth has never been this simple. Invest in our silver package and make a difference in your life. </p>
        <h3> KSh 2,000</h3>
        <!-- <div class="d-flex align-items-center justify-content-between rounded-pill bg-light px-3 py-2 mt-4"> -->
            <button type="button" class="btn btn-warning btn-rounded">
                <a href="{% url 'fortune:product3' %}">
                  BUY PACKAGE
              </a>
          </button>

      <hr>
  </div>
</div>
</div>

<br>
<hr>
<br>
<br>

<div class="row text-center">
    <div class="col-lg">
        <div class="bg-white rounded shadow-sm"> <img src="/static/fortune/images/platinum.png" alt="" width="300" height="300">
            <h5> <u>PLATINUM PACKAGE<</u></h5>
            <p class="small text-muted mb-0">Create Stable income by investing in our Platinum package and make achievement of your goals a reality.  </p>
            <h3> KSh 5,000</h3>
            <!-- <div class="d-flex align-items-center justify-content-between rounded-pill bg-light px-3 py-2 mt-4"> -->
                <button type="button" class="btn btn-warning btn-rounded">
                    <a href="{% url 'fortune:product4' %}">
                      BUY PACKAGE
                  </a>
              </button>
          <hr>
      </div>
  </div>

  <div class="col-lg">
    <div class="bg-white rounded shadow-sm"><img src="/static/fortune/images/gold.png" alt="" width="300" height="300">
        <h5> <u>GOLD PACKAGE</u></h5>
        <p class="small text-muted mb-0">Gold package is for people who needs to create wealth in a short span and experience the freedom of money. </p>
        <h3> KSh 10,000</h3>
        <!-- <div class="d-flex align-items-center justify-content-between rounded-pill bg-light px-3 py-2 mt-4"> -->
            <button type="button" class="btn btn-warning btn-rounded">
                <a href="{% url 'fortune:product5' %}">
                  BUY PACKAGE
              </a>
          </button>
      <hr>
  </div>
</div>

<div class="col-lg">
    <div class="bg-white rounded shadow-sm"><img src="/static/fortune/images/vip.png" alt="" width="300" height="300">
        <h5> <u>VIP PACKAGE</u></h5>
        <p class="small text-muted mb-0">VIP package is the package for investors who go beyond their reach. Enjoy hyper returns with VIP package and retire early.</p>
        <h3> KSh 15,000</h3>
        <!-- <div class="d-flex align-items-center justify-content-between rounded-pill bg-light px-3 py-2 mt-4"> -->
            <button type="button" class="btn btn-warning btn-rounded">
                <a href="{% url 'fortune:product6' %}">
                  BUY PACKAGE
              </a>
          </button>
      <hr>
  </div>
</div>
</div>
<hr>
</div>
<br><br><br>


<!-- Footer -->
<footer class="footer">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2022 Copyright:
    <a href="https://fortunemakers.co.ke/"> Fortune Makers</a>
</div>
<!-- Copyright -->

</footer>

{% endblock %}

<!-- jQuery library -->
<script src="{% static 'index/js/header.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.1/js/mdb.min.js"></script>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

fortune_makers/fortune/templates/fortune/product2.html
{% extends 'fortune/product1.html' %}

fortune_makers/fortune/templates/fortune/product3.html
{% extends 'fortune/product1.html' %}

fortune_makers/fortune/templates/fortune/product4.html
{% extends 'fortune/product1.html' %}

fortune_makers/fortune/templates/fortune/product5.html
{% extends 'fortune/product1.html' %}